### ISSUE TITLE
Alternate name than 'neuropil' when saving Caiman denoised calcium traces?

### ISSUE THREAD

**Issue by EricThomson** [catalystneuro/roiextractors#287]
First, thanks a lot for making neuroconv and roiextractors. I just started today and it was incredibly  easy to use -- I got things working really quickly with it.  I have an annoying question about nomenclature, as I'm relatively new to this I'm probably just missing something.

I'm planning to rebuild Caiman's save nwb functionality using neuroconv. My main question is about the nomenclature. If I understand correctly, the three time series being saved are  `Neuropil`, `Deconvolved`, and `DfOverF`. These correspond to Caiman's `estimates.C` (denoised calcium traces), `estimates.S` (spike counts from deconvolution), and `estimates.F_dff`. 

 My main concern/question is whether there might be another name available within the nwb ophys universe for Caiman's denoised calcium traces in C than `Neuropil` (my concern is that 'neuropil' typically refers to background noise that nobody wants to look at)? E.g., is there some taxonomy of time series in nwb ophys that includes other types of calcium time series?

I apologize for bringing up a terminological rather than substantive concern here -- it is only because everything else is working so well!

**Comment by CodyCBakerPhD** [comment]
> I apologize for bringing up a terminological rather than substantive concern here -- it is only because everything else is working so well!

We love these kinds of discussions. I will let @alessandratrapani explain our current understanding as we've been discussing exactly these types of things for the past ~4 months now

**Comment by alessandratrapani** [comment]
Hi @EricThomson! 
I see the problem here, which is also related to this [issue](https://github.com/catalystneuro/roiextractors/issues/249#issuecomment-1955711025).

- `estimates.C` (denoised calcium traces) should be stored in `Fluorescence` as a `ROIResponseSeries` (`_roi_response_raw` in the `SegmentationExtractor`), 
- `estimates.S` (spike counts from deconvolution) should also be stored in `Fluorescence` as a `ROIResponseSeries` named `Deconvolved` (`_roi_response_deconvolved` in the `SegmentationExtractor`)
- `estimates.F_dff` --> in `DfOverF` as a `ROIResponseSeries` named `DfOverF`  (`_roi_response_dff` in the `SegmentationExtractor`), 
- `estimates.f` (temporal background components) should be stored in Fluorescence as a `ROIResponseSeries` named either `Neuropil` or `Background` (`_roi_response_neuropil` in the `SegmentationExtractor`). Here, we should also add the spatial background components `estimates.b` and create the appropriate plane segmentation.

It is very important to keep this information for data reuse purposes. For instance, to check the quality of the segmentation output, one might want to compute indices that need the background signal to be estimated, e.g., the “isolation distance” of a cell’s signal from the surrounding signals (computed similarly to the [spike sorting equivalent](https://pubmed.ncbi.nlm.nih.gov/15680687/)).

This is something we need to fix on our end. I will work on this in the next few days.
CCing @pauladkisson to keep him updated

**Comment by EricThomson** [comment]
This sounds like a really good solution (if people really want residuals they can subtract denoised traces from raw traces). 😄

**Comment by alessandratrapani** [comment]
> On the background model: things get more gnarly for the background model when we run CNMFE in Caiman, because then there is no `b`/`f` (they are `None`). Instead, we have the ring model, so the parameters are `W` and `b0` (as I'm sure you know, in CNMFE there is a much more complicated background model, where each _pixel_ has its own background fluctuations a certain distance in a ring from that pixel that are subtracted out -- this is captured in `W` that represents the ring model; `b0` is a dc offset for each pixel). Currently I'm working on getting CNMF -> NWB to work well. Next step I plan to tackle CNMFE.

For this, we can open another issue and discuss it there. Please tag me in anything I can help with for the CNMFE --> NWB future implementation. During my PhD studies, I worked with 1p imaging data and used CNMFE for the segmentation step. I am not an expert but I can offer some help.

**Comment by EricThomson** [comment]
Awesome that sou

> For this, we can open another issue and discuss it there. Please tag me in anything I can help with for the CNMFE --> NWB future implementation

That sounds great thanks for your help!

**Comment by pauladkisson** [comment]
Closed by #291
