### ISSUE TITLE
Comments and questions

### ISSUE THREAD

**Issue by alejoe91** [catalystneuro/roiextractors#4]
Hi @bendichter  and @Saksham20 

After going through the code I have some general comments and feedback.

### Name

From the diagram in the README, I would keep the analogy with SpikeInterface in terms of terminology. 

In SI, we have `spike`+packagename (e.g. `spikeextractors`, `spiketoolkit`) and in `spikeextractors` we deal with `RecordingExtractors` and `SortingExtractors`. The spike(s) is what sorting algorithms output. So my first question is: what do you think about changing the name (still early in development) to: RoiInterface (where ROIs are what segmentation algorithms output)?

`RoiInterface` (`RI`) → RoiExtractors (`re`) → ImageExtractors (or VideoExtractors) + SegmentationExtractors

## Implementation

Back to the diagram: the `ImageExtractor` and `SegmentationExtractor` concepts are super clear. The former interfaces with the images/videos, the latter with the segmentation output files. However, they are kind of mixed up in the code. 
In my opinion, the `ImageExtractor` should have all the functions properties to read and retrieve (possibly lazily) single frames, videos, image dimensions, and all things related to the imaging.
Similarly, the `SegmentationExtractor` should take care of the segmentation output, i.e. ROIs (roi_ids, roi_pixels, masks, etc.) and (maybe) deconvolved spike times. 
Some examples of ImageExtractors will be: TiffImageExtractor, H5ImageExtractor, and possibly interfacing with the [bioformats package](https://www.openmicroscopy.org/bio-formats/) through its Python API ([python-bioformats](https://github.com/CellProfiler/python-bioformats)), which also provide a standard for imaging metadata.

The functions that do something on these objects, could live in a `roitoolkit` package. For example, `extract_deconvolved_spikes` might not be implemented in all packages, so it’s an example of something good to have.

All Extractors could derive from a `BaseExtractor` (see SI implementation [here](https://github.com/SpikeInterface/spikeextractors/blob/master/spikeextractors/baseextractor.py)) to deal with low level and shared things, like epochs, properties, dumping and loading (provenance tracking), and allocating arrays (memmap). We could even inherit directly from that class!

What do you guys think? I have some more specific comments on implementation delays, but I’ll split it in several issues over the next days :)

Cheers,
Alessio

**Comment by bendichter** [comment]
Thanks Alessio! This is really valuable feedback!

> what do you think about changing the name (still early in development) to: RoiInterface (where ROIs are what segmentation algorithms output)?

Makes sense to me, and it's more compact, which is nice. "Segmentations" is getting cumbersome because it is so long. What do you think, @Saksham20? I think I could do this pretty easily with a global find/replace in PyCharm. 

I think I'd prefer to keep the scope of current development to RoiExtractors for now as opposed to RoiInterface. For our goals, the extractors are the most important. That said, Alessio, if you want to go further, we'd be happy to collaborate with you to develop a whole "interface" platform.

I also agree about making sure ImageExtractor and `RoiExtractor` are distinct in the code. Some attributes will be shared, such as the shape of the acquisition images, but for the most part that should be split into one or the other.

> All Extractors could derive from a BaseExtractor (see SI implementation here) to deal with low level and shared things, like epochs, properties, dumping and loading (provenance tracking), and allocating arrays (memmap). We could even inherit directly from that class!

I think it's a good idea for us to share a base class. Doing it this way would require BaseRoiExtractor to `import spikeextractors`. It looks like the base dependencies of spikeextractors are very light, so I don't see a problem with this.
